CLASS_NAMES: ['Car', 'Pedestrian', 'Cyclist']

POINT_CLOUD_RANGE: [0, -40, -3, 70.4, 40, 1]

POINT_FEATURE_ENCODING:
    used_feature_list: ['x', 'y', 'z', 'intensity', 'elongation']
    src_feature_list: ['x', 'y', 'z', 'intensity', 'elongation']
    encoded_feature_dim: 5

NUM_POINT_FEATURES: 5

DATA_SPLIT:                   
    train: train
    val: val

DATA_CONFIG:
    INFO_PATH:
        train: []
        val: []

    FOV_POINTS_ONLY: True
    DROP_EMPTY_ANNOTATIONS: True

DATA_AUGMENTOR:
    DISABLE_LIST: []

DATA_PROCESSOR:
    - NAME: transform_points_to_voxels
      VOXEL_SIZE: [0.05, 0.05, 0.1]
      MAX_POINTS_PER_VOXEL: 5
      MAX_NUMBER_OF_VOXELS:
        train: 160000
        test: 160000
